name: Build Zip

on:
  push:
    branches:
      - '**'
    paths:
      - 'Plugins/METADATA-rndb-local/**'
      - 'calibre-plugin/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1
      - name: Generate commit.txt and build .mo files
        run: |
          echo "$GITHUB_SHA" > calibre-plugin/commit.txt
      - name: Shorten GITHUB_SHA
        run: echo "github_short_sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Upload plugin
        uses: actions/upload-artifact@v3
        with:
          name: METADATA-rndb-local-${{ env.github_short_sha }}
          path: |
            Plugins/METADATA-rndb-local/
            !Plugins/METADATA-rndb-local/test.py